// Seed Data and Metadata for Santa Maria Bulacan Document Management System (DMS)
// Client: Municipality of Santa Maria, Bulacan - Office of the Municipal Administrator

import {
  DocumentRecord,
  DocumentType,
  DocumentCategory,
  DocumentStatus,
  User,
  Venue,
  EventBooking,
  AuditEntry,
} from './types';

export const CURRENT_USERS: User[] = [
  {
    id: 'USR-001',
    fullName: 'Engr. Elmer B. Clemente',
    role: 'ADMINISTRATOR',
    title: 'Municipal Administrator',
    department: "Office of the Municipal Administrator",
    email: 'administrator@santamariabulacan.gov.ph',
  },
  {
    id: 'USR-002',
    fullName: 'Benito C. Fabian',
    role: 'EXECUTIVE_ASSISTANT',
    title: 'Executive Assistant II',
    department: "Office of the Municipal Administrator",
    email: 'ea.fabian@santamariabulacan.gov.ph',
  },
  {
    id: 'USR-003',
    fullName: 'Officer J. Garcia',
    role: 'OFFICER',
    title: 'Administrative Officer IV',
    department: "Office of the Municipal Administrator",
    email: 'jgarcia@santamariabulacan.gov.ph',
  },
  {
    id: 'USR-004',
    fullName: 'Sherelyn O. Libao',
    role: 'CLERK_ENCODER',
    title: 'Administrative Aide VI (Records Custodian)',
    department: "Office of the Municipal Administrator",
    email: 'records.slibao@santamariabulacan.gov.ph',
  },
];

export const VENUE_LABELS: Record<Venue, { label: string; capacity: number; location: string }> = {
  CONFERENCE_ROOM: {
    label: 'Municipal Conference Room',
    capacity: 35,
    location: '2nd Floor, Municipal Hall Main Building',
  },
  COMMAND_CENTER: {
    label: 'Command Center Room',
    capacity: 20,
    location: 'Ground Floor, Disaster Risk Reduction Bldg',
  },
  SOCIAL_HALL: {
    label: 'Municipal Social Hall',
    capacity: 250,
    location: '3rd Floor, Legislative and Civic Center',
  },
  GYMNASIUM: {
    label: 'Municipal Gymnasium',
    capacity: 1200,
    location: 'Municipal Sports Complex, Poblacion',
  },
  MAYOR_OFFICE: {
    label: "Mayor's Conference Room",
    capacity: 15,
    location: "Executive Wing, 2nd Floor, Municipal Hall",
  },
  ADMIN_OFFICE: {
    label: "Administrator's Office",
    capacity: 12,
    location: "Ground Floor, East Wing, Municipal Hall",
  },
};

export const DOCUMENT_TYPE_LABELS: Record<DocumentType, { label: string; prefix: string; color: string }> = {
  INCOMING: { label: 'General Incoming Request', prefix: 'IN', color: '#0B2545' },
  TRAVEL_ORDER: { label: 'Travel Order Request', prefix: 'TO', color: '#15803D' },
  VENUE_REQ: { label: 'Venue Reservation Request', prefix: 'VR', color: '#081E36' },
  VEHICLE_REQ: { label: 'Vehicle Dispatch Request', prefix: 'VH', color: '#2563EB' },
  FOOD_REQ: { label: 'Food and Catering Request', prefix: 'FD', color: '#9333EA' },
  OVERTIME_REQ: { label: 'Overtime Authority Request', prefix: 'OT', color: '#334155' },
  ENDORSEMENT: { label: 'Indorsement Request', prefix: 'IND', color: '#0D9488' },
  PERMIT: { label: 'Permit and Clearance Endorsement', prefix: 'PM', color: '#4F46E5' },
  LEGAL_OPINION: { label: 'Request for Legal Opinion', prefix: 'LO', color: '#7C3AED' },
  OTHER: { label: 'Other Administrative Document', prefix: 'DOC', color: '#475569' },
};

export const DOCUMENT_CATEGORY_LABELS: Record<DocumentCategory, string> = {
  EXEC_ORDER: 'Executive Order (EO)',
  SB_ENDORSEMENT: 'Sangguniang Bayan (SB) Endorsement',
  CONTRACT: 'Contract and Agreement',
  CERTIFICATION: 'Certification and Clearance',
  PERMIT: 'Special Permit',
  MEMO_ORDER: 'Memorandum Order',
  LEGAL_ADVICE: 'Legal Advice and Opinion',
  WORK_ENDORSEMENT: 'Work Financial Endorsement',
  COMM_LETTER: 'Official Communication Letter',
  OTHER: 'Miscellaneous Record',
};

export const DOCUMENT_STATUS_META: Record<
  DocumentStatus,
  { label: string; stepNumber: number; badgeCls: string; description: string }
> = {
  RECEIVED: {
    label: 'Received / Logged',
    stepNumber: 1,
    badgeCls: 'badge-received',
    description: 'Document logged at Reception desk, barcode control assigned.',
  },
  SCREENING: {
    label: 'Under Screening',
    stepNumber: 2,
    badgeCls: 'badge-screening',
    description: 'Verifying completeness of attachments and proper signatory.',
  },
  PREPARATION: {
    label: 'Preparation / Drafting',
    stepNumber: 3,
    badgeCls: 'badge-preparation',
    description: 'Assigned Officer drafting response, executive order, or routing paper.',
  },
  REVIEW: {
    label: 'Pending Executive Review',
    stepNumber: 4,
    badgeCls: 'badge-review',
    description: 'Submitted to Municipal Administrator and Executive Assistant for evaluation.',
  },
  APPROVED: {
    label: 'Approved',
    stepNumber: 4,
    badgeCls: 'badge-approved',
    description: 'Formally approved by the Municipal Administrator or Mayor.',
  },
  ENDORSED: {
    label: 'Endorsed',
    stepNumber: 4,
    badgeCls: 'badge-endorsed',
    description: 'Formally endorsed to Sangguniang Bayan or relevant external agency.',
  },
  DENIED: {
    label: 'Returned / Denied',
    stepNumber: 4,
    badgeCls: 'badge-denied',
    description: 'Disapproved with documented grounds and statutory legal notes.',
  },
  TRANSMITTED: {
    label: 'Transmitted / Outgoing',
    stepNumber: 5,
    badgeCls: 'badge-transmitted',
    description: 'Dispatched to requesting department or citizen with signed receipt.',
  },
  CLOSED: {
    label: 'Closed / Archived',
    stepNumber: 6,
    badgeCls: 'badge-closed',
    description: 'Transaction concluded. Stored in municipal digital archive.',
  },
};

export const INITIAL_DOCUMENTS: DocumentRecord[] = [
  {
    id: 'DOC-2026-0001',
    controlNumber: 'TO-2026-0045',
    type: 'TRAVEL_ORDER',
    category: 'OTHER',
    title: 'Travel Order Request - Engr. Santos for DILG Regional Consultative Assembly',
    requestingParty: 'Engr. Roberto Santos',
    originOffice: 'Municipal Engineering Office',
    dateReceived: '2026-09-30T08:30:00+08:00',
    assignedTo: 'Officer J. Garcia',
    status: 'REVIEW',
    priority: 'HIGH',
    scannedFileUrl: '/assets/sample-travel-order.pdf',
    attachments: [
      {
        id: 'ATT-001',
        fileName: 'DILG_Advisory_Regional_Assembly.pdf',
        fileSize: '1.4 MB',
        fileType: 'application/pdf',
        uploadedBy: 'Sherelyn O. Libao',
        uploadedAt: '2026-09-30T08:35:00+08:00',
      },
      {
        id: 'ATT-002',
        fileName: 'Itinerary_of_Travel_Engr_Santos.pdf',
        fileSize: '820 KB',
        fileType: 'application/pdf',
        uploadedBy: 'Sherelyn O. Libao',
        uploadedAt: '2026-09-30T08:35:00+08:00',
      },
    ],
    draftContent: `PAMAHALAANG BAYAN NG SANTA MARIA, BULACAN
TANGGAPAN NG PUNONG BAYAN / MUNICIPAL ADMINISTRATOR
Poblacion, Santa Maria, Bulacan 3022

TRAVEL ORDER NO. TO-2026-0045

TO: ENGR. ROBERTO SANTOS, Municipal Engineer
DESTINATION: DILG Regional Office III, City of San Fernando, Pampanga
PURPOSE: Official Attendance at the Regional Consultative Meeting on Infrastructure Projects
DATE OF TRAVEL: October 2, 2026
APPROPRIATION: Travelling Expenses chargeable against LGU Funds subject to existing COA rules.`,
    draftDocumentUrl: null,
    denialReason: null,
    endorsementNotes: 'Recommended for immediate approval. DILG assembly is mandatory.',
    transmissionDetails: null,
    slaDeadline: '2026-10-03T17:00:00+08:00',
    isOverdue: false,
    createdBy: 'Sherelyn O. Libao',
    createdAt: '2026-09-30T08:30:00+08:00',
    updatedAt: '2026-09-30T10:15:00+08:00',
  },
  {
    id: 'DOC-2026-0002',
    controlNumber: 'IN-2026-0911',
    type: 'ENDORSEMENT',
    category: 'SB_ENDORSEMENT',
    title: 'SB Endorsement - Resolution No. 2026-089: Appropriation of Supplementary Funds for Senior Citizens Assistance Program',
    requestingParty: 'Atty. Cecilia Ramos (SB Secretary)',
    originOffice: 'Sangguniang Bayan Secretariat',
    dateReceived: '2026-09-28T09:00:00+08:00',
    assignedTo: 'Officer J. Garcia',
    status: 'CLOSED',
    priority: 'NORMAL',
    scannedFileUrl: '/assets/sample-sb-endorsement.pdf',
    attachments: [
      {
        id: 'ATT-003',
        fileName: 'Draft_SB_Resolution_2026_089.pdf',
        fileSize: '3.1 MB',
        fileType: 'application/pdf',
        uploadedBy: 'Sherelyn O. Libao',
        uploadedAt: '2026-09-28T09:10:00+08:00',
      },
    ],
    draftContent: `1st Indorsement
Respectfully referred to the Honorable Sangguniang Bayan of Santa Maria, Bulacan, recommending favorable legislative action for Resolution No. 2026-089.`,
    draftDocumentUrl: null,
    denialReason: null,
    endorsementNotes: 'Endorsed to SB Committee on Appropriations on Sept 29, 2026.',
    transmissionDetails: {
      transmittedDate: '2026-09-29T14:30:00+08:00',
      transmittedToOffice: 'Sangguniang Bayan Secretariat',
      recipientName: 'Atty. Cecilia Ramos',
      receivedBy: 'Ms. Marilou Perez (SB Receiving Clerk)',
      notes: 'Received original 3 sets with annexes.',
    },
    slaDeadline: '2026-10-01T17:00:00+08:00',
    isOverdue: false,
    createdBy: 'Sherelyn O. Libao',
    createdAt: '2026-09-28T09:00:00+08:00',
    updatedAt: '2026-09-29T16:00:00+08:00',
  },
  {
    id: 'DOC-2026-0003',
    controlNumber: 'VR-2026-0112',
    type: 'VENUE_REQ',
    category: 'OTHER',
    title: 'Venue Request - PESO Office for Municipal Megajob Fair 2026 (Social Hall)',
    requestingParty: 'Maria Elena Reyes (PESO Manager)',
    originOffice: 'Public Employment Service Office (PESO)',
    dateReceived: '2026-09-29T11:00:00+08:00',
    assignedTo: 'Sherelyn O. Libao',
    status: 'APPROVED',
    priority: 'HIGH',
    scannedFileUrl: '/assets/sample-venue-request.pdf',
    attachments: [
      {
        id: 'ATT-004',
        fileName: 'Megajob_Fair_Proposal_PESO.pdf',
        fileSize: '2.5 MB',
        fileType: 'application/pdf',
        uploadedBy: 'Sherelyn O. Libao',
        uploadedAt: '2026-09-29T11:05:00+08:00',
      },
    ],
    draftContent: `MEMORANDUM FOR VENUE CLEARANCE: Social Hall approved for October 15, 2026 from 08:00 AM to 05:00 PM. Coordination with General Services Office (GSO) required for sound and tables.`,
    draftDocumentUrl: null,
    denialReason: null,
    endorsementNotes: 'Approved by Municipal Administrator. Forwarded to GSO for logistics setup.',
    transmissionDetails: null,
    slaDeadline: '2026-10-02T17:00:00+08:00',
    isOverdue: false,
    createdBy: 'Sherelyn O. Libao',
    createdAt: '2026-09-29T11:00:00+08:00',
    updatedAt: '2026-09-30T09:20:00+08:00',
  },
  {
    id: 'DOC-2026-0004',
    controlNumber: 'EO-2026-0018',
    type: 'INCOMING',
    category: 'EXEC_ORDER',
    title: 'Request for Executive Order - Reconstitution and Strengthening of the Municipal Anti-Drug Abuse Council (MADAC)',
    requestingParty: 'PMAJ Jonathan V. Cruz',
    originOffice: 'Santa Maria Municipal Police Station (PNP)',
    dateReceived: '2026-09-27T08:00:00+08:00',
    assignedTo: 'Officer J. Garcia',
    status: 'REVIEW',
    priority: 'URGENT',
    scannedFileUrl: '/assets/sample-madac-request.pdf',
    attachments: [
      {
        id: 'ATT-005',
        fileName: 'DILG_Memorandum_Circular_MADAC_Audit.pdf',
        fileSize: '4.2 MB',
        fileType: 'application/pdf',
        uploadedBy: 'Sherelyn O. Libao',
        uploadedAt: '2026-09-27T08:15:00+08:00',
      },
    ],
    draftContent: `EXECUTIVE ORDER NO. 2026-018
RECONSTITUTING AND STRENGTHENING THE MUNICIPAL ANTI-DRUG ABUSE COUNCIL (MADAC) OF SANTA MARIA, BULACAN, DEFINING ITS POWERS, FUNCTIONS, AND COMPOSITION IN ACCORDANCE WITH DILG MEMORANDUM CIRCULAR NO. 2023-145`,
    draftDocumentUrl: null,
    denialReason: null,
    endorsementNotes: 'Draft Executive Order prepared. Requires final review by Municipal Administrator and signature of the Municipal Mayor.',
    transmissionDetails: null,
    slaDeadline: '2026-09-30T17:00:00+08:00',
    isOverdue: true,
    createdBy: 'Sherelyn O. Libao',
    createdAt: '2026-09-27T08:00:00+08:00',
    updatedAt: '2026-09-30T11:00:00+08:00',
  },
  {
    id: 'DOC-2026-0005',
    controlNumber: 'LO-2026-0012',
    type: 'LEGAL_OPINION',
    category: 'LEGAL_ADVICE',
    title: 'Request for Legal Opinion - Contractual Validity and Retention Clause with ABC Construction and Supply Corp.',
    requestingParty: 'Engr. Elmer B. Clemente',
    originOffice: 'Office of the Municipal Administrator',
    dateReceived: '2026-09-30T09:15:00+08:00',
    assignedTo: 'Officer J. Garcia',
    status: 'PREPARATION',
    priority: 'HIGH',
    scannedFileUrl: null,
    attachments: [
      {
        id: 'ATT-006',
        fileName: 'Contract_Agreement_ABC_Construction.pdf',
        fileSize: '5.8 MB',
        fileType: 'application/pdf',
        uploadedBy: 'Officer J. Garcia',
        uploadedAt: '2026-09-30T09:30:00+08:00',
      },
    ],
    draftContent: 'Drafting request transmittal to Municipal Legal Officer Atty. Gerald Santos.',
    draftDocumentUrl: null,
    denialReason: null,
    endorsementNotes: null,
    transmissionDetails: null,
    slaDeadline: '2026-10-03T17:00:00+08:00',
    isOverdue: false,
    createdBy: 'Officer J. Garcia',
    createdAt: '2026-09-30T09:15:00+08:00',
    updatedAt: '2026-09-30T09:45:00+08:00',
  },
  {
    id: 'DOC-2026-0006',
    controlNumber: 'IN-2026-0944',
    type: 'INCOMING',
    category: 'COMM_LETTER',
    title: 'Notice of Meeting - ADAC Performance Audit and Awards Committee Deliberation',
    requestingParty: 'LGOO VI Ma. Teresa D. Santiago',
    originOffice: 'DILG Municipal Operations Office',
    dateReceived: '2026-09-30T10:00:00+08:00',
    assignedTo: null,
    status: 'SCREENING',
    priority: 'NORMAL',
    scannedFileUrl: null,
    attachments: [
      {
        id: 'ATT-007',
        fileName: 'DILG_Notice_ADAC_Deliberation.pdf',
        fileSize: '950 KB',
        fileType: 'application/pdf',
        uploadedBy: 'Sherelyn O. Libao',
        uploadedAt: '2026-09-30T10:05:00+08:00',
      },
    ],
    draftContent: '',
    draftDocumentUrl: null,
    denialReason: null,
    endorsementNotes: null,
    transmissionDetails: null,
    slaDeadline: '2026-10-03T17:00:00+08:00',
    isOverdue: false,
    createdBy: 'Sherelyn O. Libao',
    createdAt: '2026-09-30T10:00:00+08:00',
    updatedAt: '2026-09-30T10:05:00+08:00',
  },
  {
    id: 'DOC-2026-0007',
    controlNumber: 'OT-2026-0088',
    type: 'OVERTIME_REQ',
    category: 'OTHER',
    title: 'Overtime Request - Accounting Office Staff for CY 2026 Q3 Financial Reconciliation and COA Submission',
    requestingParty: 'Lourdes M. Fernandez (Municipal Accountant)',
    originOffice: 'Municipal Accounting Office',
    dateReceived: '2026-09-29T14:00:00+08:00',
    assignedTo: 'Benito C. Fabian',
    status: 'TRANSMITTED',
    priority: 'HIGH',
    scannedFileUrl: null,
    attachments: [
      {
        id: 'ATT-008',
        fileName: 'Accounting_Staff_OT_List_Schedule.pdf',
        fileSize: '1.1 MB',
        fileType: 'application/pdf',
        uploadedBy: 'Sherelyn O. Libao',
        uploadedAt: '2026-09-29T14:10:00+08:00',
      },
    ],
    draftContent: 'APPROVED OVERTIME AUTHORITY for 8 Accounting personnel on October 3-4, 2026.',
    draftDocumentUrl: null,
    denialReason: null,
    endorsementNotes: 'Approved by Municipal Administrator Elmer B. Clemente.',
    transmissionDetails: {
      transmittedDate: '2026-09-30T09:00:00+08:00',
      transmittedToOffice: 'Municipal Accounting Office',
      recipientName: 'Lourdes M. Fernandez',
      receivedBy: 'Carla De Jesus (Admin Staff)',
      notes: 'Transmitted copy for posting on bundy clock station.',
    },
    slaDeadline: '2026-10-02T17:00:00+08:00',
    isOverdue: false,
    createdBy: 'Sherelyn O. Libao',
    createdAt: '2026-09-29T14:00:00+08:00',
    updatedAt: '2026-09-30T09:15:00+08:00',
  },
  {
    id: 'DOC-2026-0008',
    controlNumber: 'VH-2026-0034',
    type: 'VEHICLE_REQ',
    category: 'OTHER',
    title: 'Vehicle Request - MDRRMO Rescue Van for Regional Disaster Resilience Drill in Malolos',
    requestingParty: 'Captain Arthur Mendoza',
    originOffice: 'MDRRMO',
    dateReceived: '2026-09-29T08:00:00+08:00',
    assignedTo: 'Benito C. Fabian',
    status: 'DENIED',
    priority: 'NORMAL',
    scannedFileUrl: null,
    attachments: [
      {
        id: 'ATT-009',
        fileName: 'MDRRMO_Vehicle_Trip_Ticket_Request.pdf',
        fileSize: '750 KB',
        fileType: 'application/pdf',
        uploadedBy: 'Sherelyn O. Libao',
        uploadedAt: '2026-09-29T08:15:00+08:00',
      },
    ],
    draftContent: '',
    draftDocumentUrl: null,
    denialReason: 'Vehicle Unit Van-03 scheduled for mandatory preventive maintenance on requested date. Alternative vehicle requested from Motorpool.',
    endorsementNotes: 'Disapproved with advice to coordinate with GSO for alternate service vehicle.',
    transmissionDetails: null,
    slaDeadline: '2026-10-02T17:00:00+08:00',
    isOverdue: false,
    createdBy: 'Sherelyn O. Libao',
    createdAt: '2026-09-29T08:00:00+08:00',
    updatedAt: '2026-09-29T16:45:00+08:00',
  },
];

export const INITIAL_EVENTS: EventBooking[] = [
  {
    id: 'EVT-001',
    venue: 'CONFERENCE_ROOM',
    title: 'Municipal Local Finance Committee (LFC) Budget Hearing',
    organizer: 'Lourdes Fernandez (Accounting)',
    department: 'Municipal Accounting Office',
    date: '2026-10-01',
    startTime: '09:00',
    endTime: '12:00',
    attendees: ['Mayor Bartolome', 'Engr. Clemente (MA)', 'LFC Members', 'Budget Officer'],
    involvesMayor: true,
    involvesAdmin: true,
    status: 'CONFIRMED',
    notes: 'Deliberation of CY 2027 Executive Budget allocations.',
  },
  {
    id: 'EVT-002',
    venue: 'COMMAND_CENTER',
    title: 'MDRRMC Pre-Disaster Risk Assessment (Typhoon Preparedness)',
    organizer: 'MDRRMO Chief Mendoza',
    department: 'MDRRMO',
    date: '2026-10-01',
    startTime: '13:30',
    endTime: '16:00',
    attendees: ['Engr. Clemente (MA)', 'PNP Chief', 'BFP Marshall', 'MSWDO Head'],
    involvesMayor: false,
    involvesAdmin: true,
    status: 'CONFIRMED',
    notes: 'Weather advisory bulletin briefing and rescue asset dispatch protocol.',
  },
  {
    id: 'EVT-003',
    venue: 'SOCIAL_HALL',
    title: 'Santa Maria Barangay Captains Quarterly General Assembly',
    organizer: 'Liga ng mga Barangay Secretariat',
    department: 'Liga ng mga Barangay',
    date: '2026-10-02',
    startTime: '09:00',
    endTime: '15:00',
    attendees: ['Mayor Bartolome', 'Vice Mayor Perez', 'Engr. Clemente (MA)', '24 Punong Barangays'],
    involvesMayor: true,
    involvesAdmin: true,
    status: 'CONFIRMED',
    notes: 'Distribution of Barangay Development Assistance funds.',
  },
  {
    id: 'EVT-004',
    venue: 'GYMNASIUM',
    title: 'Municipal Megajob Fair 2026 (Day 1 Recruitment Drive)',
    organizer: 'Maria Elena Reyes (PESO)',
    department: 'PESO',
    date: '2026-10-15',
    startTime: '08:00',
    endTime: '17:00',
    attendees: ['Mayor Bartolome', 'DOLE Provincial Director', '35 Participating Employers'],
    involvesMayor: true,
    involvesAdmin: false,
    status: 'CONFIRMED',
    notes: 'Logistics coordination with PNP for crowd control.',
  },
  {
    id: 'EVT-005',
    venue: 'MAYOR_OFFICE',
    title: 'Executive Courtesy Call - Bulacan Chamber of Commerce and Industry',
    organizer: 'Mayor Executive Secretariat',
    department: "Mayor's Office",
    date: '2026-10-02',
    startTime: '16:00',
    endTime: '17:00',
    attendees: ['Mayor Bartolome', 'Engr. Clemente (MA)', 'BCCI Board of Directors'],
    involvesMayor: true,
    involvesAdmin: true,
    status: 'CONFIRMED',
    notes: 'Discussion of local business tax incentives and municipal trade expo.',
  },
  {
    id: 'EVT-006',
    venue: 'ADMIN_OFFICE',
    title: 'Contract Review Deliberation - Santa Maria Public Market Redevelopment',
    organizer: 'Engr. Elmer Clemente',
    department: "Office of the Municipal Administrator",
    date: '2026-10-03',
    startTime: '10:00',
    endTime: '11:30',
    attendees: ['Engr. Clemente (MA)', 'Atty. Santos (Legal)', 'Engr. Santos (MEO)', 'Bids and Awards Committee'],
    involvesMayor: false,
    involvesAdmin: true,
    status: 'CONFIRMED',
    notes: 'Statutory compliance check on contractor performance security bonds.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditEntry[] = [
  {
    id: 'AUD-001',
    documentId: 'DOC-2026-0004',
    action: 'RECEIVED',
    userId: 'USR-004',
    userName: 'Sherelyn O. Libao',
    userRole: 'CLERK_ENCODER',
    timestamp: '2026-09-27T08:15:00+08:00',
    details: 'Received physical documents from PNP. Scanned and assigned control number EO-2026-0018.',
  },
  {
    id: 'AUD-002',
    documentId: 'DOC-2026-0004',
    action: 'SCREENED_PASS',
    userId: 'USR-004',
    userName: 'Sherelyn O. Libao',
    userRole: 'CLERK_ENCODER',
    timestamp: '2026-09-27T08:45:00+08:00',
    details: 'Screening passed. Attachment completeness verified. Forwarded to Officer J. Garcia for drafting.',
  },
  {
    id: 'AUD-003',
    documentId: 'DOC-2026-0004',
    action: 'DRAFTED',
    userId: 'USR-003',
    userName: 'Officer J. Garcia',
    userRole: 'OFFICER',
    timestamp: '2026-09-29T16:00:00+08:00',
    details: 'Draft Executive Order prepared using LGU Template. Forwarded to MA Review Queue.',
  },
  {
    id: 'AUD-004',
    documentId: 'DOC-2026-0001',
    action: 'RECEIVED',
    userId: 'USR-004',
    userName: 'Sherelyn O. Libao',
    userRole: 'CLERK_ENCODER',
    timestamp: '2026-09-30T08:35:00+08:00',
    details: 'Logged Travel Order Request from Engr. Santos. Control number TO-2026-0045 assigned.',
  },
  {
    id: 'AUD-005',
    documentId: 'DOC-2026-0001',
    action: 'DRAFTED',
    userId: 'USR-003',
    userName: 'Officer J. Garcia',
    userRole: 'OFFICER',
    timestamp: '2026-09-30T10:15:00+08:00',
    details: 'Travel Order document generated and endorsed for MA signature.',
  },
  {
    id: 'AUD-006',
    documentId: 'DOC-2026-0008',
    action: 'DENIED',
    userId: 'USR-001',
    userName: 'Engr. Elmer B. Clemente',
    userRole: 'ADMINISTRATOR',
    timestamp: '2026-09-29T16:45:00+08:00',
    details: 'Vehicle request disapproved due to scheduled mechanical maintenance.',
  },
];
