import { DocumentRecord, EventBooking, User, AuditEntry } from './types';

export const CLEAN_USERS: User[] = [
  {
    id: 'usr-admin-01',
    fullName: 'Engr. Elmer B. Clemente',
    role: 'ADMINISTRATOR',
    title: 'Municipal Administrator',
    department: 'Office of the Municipal Administrator',
    email: 'admin@santamaria.gov.ph',
  },
  {
    id: 'usr-mayor-02',
    fullName: 'Hon. Bartolome',
    role: 'ADMINISTRATOR',
    title: 'Municipal Mayor',
    department: 'Office of the Municipal Mayor',
    email: 'mayor@santamaria.gov.ph',
  },
  {
    id: 'usr-records-03',
    fullName: 'Ma. Cristina Perez',
    role: 'OFFICER',
    title: 'Administrative Officer V',
    department: 'Records and Archives Division',
    email: 'records.officer@santamaria.gov.ph',
  },
  {
    id: 'usr-legal-04',
    fullName: 'Atty. Rodrigo Ramos',
    role: 'OFFICER',
    title: 'Senior Legal Officer',
    department: 'Municipal Legal Office',
    email: 'legal@santamaria.gov.ph',
  },
  {
    id: 'usr-clerk-05',
    fullName: 'Juan Dela Cruz',
    role: 'CLERK_ENCODER',
    title: 'Administrative Aide IV',
    department: 'Central Receiving Desk',
    email: 'clerk@santamaria.gov.ph',
  },
];

export const CLEAN_DOCUMENTS: DocumentRecord[] = [
  {
    id: 'doc-001',
    controlNumber: 'TO-2026-0042',
    type: 'TRAVEL_ORDER',
    category: 'ADMINISTRATIVE' as any,
    title: 'Request for Travel Order - Provincial Disaster Risk Reduction and Management Council Quarterly Coordination Conference',
    requestingParty: 'Mr. Florian De Leon',
    originOffice: 'Municipal Disaster Risk Reduction and Management Office (MDRRMO)',
    dateReceived: '2026-09-28T09:30:00.000Z',
    assignedTo: 'Engr. Elmer B. Clemente',
    status: 'REVIEW',
    scannedFileUrl: null,
    attachments: [],
    slaDeadline: '2026-10-01T09:30:00.000Z',
    isOverdue: false,
    priority: 'NORMAL',
    denialReason: null,
    endorsementNotes: 'Endorsed to Municipal Administrator for final counter-signature and per diem release.',
    createdBy: 'Juan Dela Cruz',
    createdAt: '2026-09-28T09:30:00.000Z',
    updatedAt: '2026-09-29T10:00:00.000Z',
  },
  {
    id: 'doc-002',
    controlNumber: 'EO-2026-0018',
    type: 'INCOMING',
    category: 'EXEC_ORDER',
    title: 'Executive Order - Reconstitution and Strengthening of the Municipal Anti-Drug Abuse Council (MADAC)',
    requestingParty: 'P/Lt. Col. Arthur Gomez',
    originOffice: 'Philippine National Police - Santa Maria Municipal Police Station',
    dateReceived: '2026-09-25T14:15:00.000Z',
    assignedTo: 'Hon. Bartolome',
    status: 'REVIEW',
    scannedFileUrl: null,
    attachments: [],
    slaDeadline: '2026-09-28T14:15:00.000Z',
    isOverdue: true,
    priority: 'URGENT',
    denialReason: null,
    endorsementNotes: 'SLA escalation memorandum generated pursuant to RA 11032 Section 21.',
    createdBy: 'Juan Dela Cruz',
    createdAt: '2026-09-25T14:15:00.000Z',
    updatedAt: '2026-09-28T14:15:00.000Z',
  },
  {
    id: 'doc-003',
    controlNumber: 'IN-2026-0944',
    type: 'ENDORSEMENT',
    category: 'SB_ENDORSEMENT',
    title: '1st Indorsement - Proposed Barangay Poblacion Ordinance No. 04 S-2026 Regulating Tricycle Terminal Zones',
    requestingParty: 'Punong Barangay Reynaldo Ramos',
    originOffice: 'Barangay Council of Poblacion',
    dateReceived: '2026-09-30T10:00:00.000Z',
    assignedTo: null,
    status: 'SCREENING',
    scannedFileUrl: null,
    attachments: [],
    slaDeadline: '2026-10-03T10:00:00.000Z',
    isOverdue: false,
    priority: 'NORMAL',
    denialReason: null,
    endorsementNotes: null,
    createdBy: 'Juan Dela Cruz',
    createdAt: '2026-09-30T10:00:00.000Z',
    updatedAt: '2026-09-30T10:00:00.000Z',
  },
  {
    id: 'doc-004',
    controlNumber: 'VR-2026-0089',
    type: 'VENUE_REQ',
    category: 'PERMIT',
    title: 'Application for Venue Clearance - 2026 Municipal Inter-Barangay Athletic League and Sports Festival',
    requestingParty: 'Hon. Kenneth Bautista (SK President)',
    originOffice: 'Sangguniang Kabataan Federation of Santa Maria',
    dateReceived: '2026-09-27T11:20:00.000Z',
    assignedTo: 'Engr. Elmer B. Clemente',
    status: 'APPROVED',
    scannedFileUrl: null,
    attachments: [],
    slaDeadline: '2026-09-30T11:20:00.000Z',
    isOverdue: false,
    priority: 'HIGH',
    denialReason: null,
    endorsementNotes: 'Approved with General Services Office coordination for sound and security.',
    createdBy: 'Juan Dela Cruz',
    createdAt: '2026-09-27T11:20:00.000Z',
    updatedAt: '2026-09-28T16:00:00.000Z',
  },
  {
    id: 'doc-005',
    controlNumber: 'OT-2026-0155',
    type: 'OVERTIME_REQ',
    category: 'WORK_ENDORSEMENT',
    title: 'Authority to Render Overtime Services - Revenue Assessment and Real Property Tax Collection Operations',
    requestingParty: 'Ms. Carmelita Cruz',
    originOffice: 'Municipal Assessor\'s Office',
    dateReceived: '2026-09-26T08:45:00.000Z',
    assignedTo: 'Engr. Elmer B. Clemente',
    status: 'TRANSMITTED',
    scannedFileUrl: null,
    attachments: [],
    slaDeadline: '2026-09-29T08:45:00.000Z',
    isOverdue: false,
    priority: 'NORMAL',
    denialReason: null,
    endorsementNotes: 'Authorized subject to Civil Service Commission and COA auditing rules.',
    transmissionDetails: {
      transmittedDate: '2026-09-28T15:30:00.000Z',
      transmittedToOffice: 'Accounting and Budget Division',
      recipientName: 'Carmelita Cruz',
      receivedBy: 'Analyn Mendoza (Clerk)',
      notes: 'Physical copy signed and acknowledged in dispatch logbook folio 88.',
    },
    createdBy: 'Juan Dela Cruz',
    createdAt: '2026-09-26T08:45:00.000Z',
    updatedAt: '2026-09-28T15:30:00.000Z',
  },
  {
    id: 'doc-006',
    controlNumber: 'LO-2026-0012',
    type: 'LEGAL_OPINION',
    category: 'LEGAL_ADVICE',
    title: 'Request for Legal Opinion - Terms of Memorandum of Agreement for Santa Maria Riverbank Protection Project',
    requestingParty: 'Engr. Roberto Santos',
    originOffice: 'Municipal Engineering Office',
    dateReceived: '2026-09-29T13:00:00.000Z',
    assignedTo: 'Atty. Rodrigo Ramos',
    status: 'PREPARATION',
    scannedFileUrl: null,
    attachments: [],
    slaDeadline: '2026-10-02T13:00:00.000Z',
    isOverdue: false,
    priority: 'HIGH',
    denialReason: null,
    endorsementNotes: null,
    createdBy: 'Juan Dela Cruz',
    createdAt: '2026-09-29T13:00:00.000Z',
    updatedAt: '2026-09-29T13:00:00.000Z',
  },
  {
    id: 'doc-007',
    controlNumber: 'CR-2026-0311',
    type: 'INCOMING',
    category: 'CERTIFICATION',
    title: 'Public Hearing Resolution - Application for Special Permit for Farm-to-Market Road Construction in Barangay Catmon',
    requestingParty: 'Mr. Danilo Castro',
    originOffice: 'Catmon Farmers Cooperative',
    dateReceived: '2026-09-22T10:30:00.000Z',
    assignedTo: 'Ma. Cristina Perez',
    status: 'CLOSED',
    scannedFileUrl: null,
    attachments: [],
    slaDeadline: '2026-09-25T10:30:00.000Z',
    isOverdue: false,
    priority: 'NORMAL',
    denialReason: null,
    endorsementNotes: 'Concluded and archived in digital repository shelf R-04-B.',
    createdBy: 'Juan Dela Cruz',
    createdAt: '2026-09-22T10:30:00.000Z',
    updatedAt: '2026-09-25T16:00:00.000Z',
  },
  {
    id: 'doc-008',
    controlNumber: 'MO-2026-0005',
    type: 'INCOMING',
    category: 'MEMO_ORDER',
    title: 'Office Memorandum - Observance of Regular Working Hours and Biometric Attendance Logging',
    requestingParty: 'Atty. Rodrigo Ramos',
    originOffice: 'Human Resource Management Office (HRMO)',
    dateReceived: '2026-09-20T08:00:00.000Z',
    assignedTo: 'Engr. Elmer B. Clemente',
    status: 'CLOSED',
    scannedFileUrl: null,
    attachments: [],
    slaDeadline: '2026-09-23T08:00:00.000Z',
    isOverdue: false,
    priority: 'NORMAL',
    denialReason: null,
    endorsementNotes: 'Transmitted to all departments and logged into municipal permanent archives.',
    transmissionDetails: {
      transmittedDate: '2026-09-22T14:00:00.000Z',
      transmittedToOffice: 'All Municipal Departments',
      recipientName: 'General Circulation',
      receivedBy: 'Administrative Records Clerk',
      notes: 'Broadcast transmittal to all department head inboxes.',
    },
    createdBy: 'Juan Dela Cruz',
    createdAt: '2026-09-20T08:00:00.000Z',
    updatedAt: '2026-09-22T14:00:00.000Z',
  },
];

export const CLEAN_EVENTS: EventBooking[] = [
  {
    id: 'evt-001',
    venue: 'CONFERENCE_ROOM',
    title: 'Municipal Local Finance Committee (LFC) Budget Hearing',
    organizer: 'Lourdes Fernandez',
    department: 'Municipal Accounting Office',
    date: '2026-10-01',
    startTime: '09:00',
    endTime: '12:00',
    attendees: ['Hon. Bartolome', 'Engr. Elmer B. Clemente'],
    involvesMayor: true,
    involvesAdmin: true,
    status: 'CONFIRMED',
    notes: 'Sound system and projector clearance logged.',
  },
  {
    id: 'evt-002',
    venue: 'COMMAND_CENTER',
    title: 'MDRRMO Pre-Disaster Risk Assessment (Typhoon Preparedness)',
    organizer: 'Florian De Leon',
    department: 'MDRRMO',
    date: '2026-10-01',
    startTime: '13:30',
    endTime: '16:00',
    attendees: ['Engr. Elmer B. Clemente'],
    involvesMayor: false,
    involvesAdmin: true,
    status: 'CONFIRMED',
    notes: 'Emergency broadcast equipment standby.',
  },
  {
    id: 'evt-003',
    venue: 'SOCIAL_HALL',
    title: 'Santa Maria Barangay Captains Quarterly General Assembly',
    organizer: 'Liga ng mga Barangay Secretariat',
    department: 'Liga ng mga Barangay',
    date: '2026-10-02',
    startTime: '09:00',
    endTime: '15:00',
    attendees: ['Hon. Bartolome', 'Engr. Elmer B. Clemente'],
    involvesMayor: true,
    involvesAdmin: true,
    status: 'CONFIRMED',
    notes: 'Catering and peace and order personnel deployed.',
  },
  {
    id: 'evt-004',
    venue: 'GYMNASIUM',
    title: 'Municipal Megajob Fair 2026 (Day 1 Recruitment Drive)',
    organizer: 'Maria Elena Reyes',
    department: 'Public Employment Service Office (PESO)',
    date: '2026-10-15',
    startTime: '08:00',
    endTime: '17:00',
    attendees: ['Hon. Bartolome'],
    involvesMayor: true,
    involvesAdmin: false,
    status: 'CONFIRMED',
    notes: 'Security deployment by PNP Santa Maria.',
  },
  {
    id: 'evt-005',
    venue: 'SESSION_HALL' as any,
    title: 'Sangguniang Bayan 42nd Regular Legislative Session',
    organizer: 'Vice Mayor and Presiding Officer',
    department: 'Sangguniang Bayan',
    date: '2026-10-06',
    startTime: '09:00',
    endTime: '14:00',
    attendees: [],
    involvesMayor: false,
    involvesAdmin: false,
    status: 'CONFIRMED',
    notes: 'Legislative audio recording system activated.',
  },
  {
    id: 'evt-006',
    venue: 'PLAZA_STAGE' as any,
    title: 'Araw ng Santa Maria Cultural Presentation & Civic Awards',
    organizer: 'Municipal Tourism and Cultural Affairs',
    department: 'Tourism Office',
    date: '2026-10-20',
    startTime: '17:00',
    endTime: '22:00',
    attendees: ['Hon. Bartolome', 'Engr. Elmer B. Clemente'],
    involvesMayor: true,
    involvesAdmin: true,
    status: 'CONFIRMED',
    notes: 'Traffic rerouting advisory issued for Poblacion.',
  },
];

export const CLEAN_AUDIT_LOGS: AuditEntry[] = [
  {
    id: 'aud-001',
    documentId: 'doc-001',
    action: 'RECEIVED',
    userId: 'usr-clerk-05',
    userName: 'Juan Dela Cruz',
    userRole: 'CLERK_ENCODER',
    timestamp: '2026-09-28T09:30:00.000Z',
    details: 'Document received at Central Receiving Desk. Control number TO-2026-0042 assigned.',
  },
  {
    id: 'aud-002',
    documentId: 'doc-001',
    action: 'SCREENED_PASS' as any,
    userId: 'usr-clerk-05',
    userName: 'Juan Dela Cruz',
    userRole: 'CLERK_ENCODER',
    timestamp: '2026-09-28T10:15:00.000Z',
    details: 'Screening checklist verified. Annexes complete with official invitations attached.',
  },
  {
    id: 'aud-003',
    documentId: 'doc-002',
    action: 'SUBMITTED_REVIEW' as any,
    userId: 'usr-admin-01',
    userName: 'Engr. Elmer B. Clemente',
    userRole: 'ADMINISTRATOR',
    timestamp: '2026-09-26T11:00:00.000Z',
    details: 'Transmitted to Mayor\'s desk. SLA alert triggered due to expiration of 72-hour window.',
  },
  {
    id: 'aud-004',
    documentId: 'doc-004',
    action: 'APPROVED',
    userId: 'usr-admin-01',
    userName: 'Engr. Elmer B. Clemente',
    userRole: 'ADMINISTRATOR',
    timestamp: '2026-09-27T16:45:00.000Z',
    details: 'Executive approval stamped. Routing slip signed for GSO logistics coordination.',
  },
  {
    id: 'aud-005',
    documentId: 'doc-005',
    action: 'TRANSMITTED',
    userId: 'usr-clerk-05',
    userName: 'Juan Dela Cruz',
    userRole: 'CLERK_ENCODER',
    timestamp: '2026-09-28T15:30:00.000Z',
    details: 'Dispatched to Municipal Assessor\'s Office with physical transmittal receipt.',
  },
  {
    id: 'aud-006',
    eventId: 'evt-001',
    action: 'SCHEDULED_EVENT',
    userId: 'usr-admin-01',
    userName: 'Engr. Elmer B. Clemente',
    userRole: 'ADMINISTRATOR',
    timestamp: '2026-09-29T14:00:00.000Z',
    details: 'Scheduled Municipal Local Finance Committee Budget Hearing at Conference Room.',
  },
];
